### ISSUE TITLE
Caret browsing causes strange behavior in the web REPL

### ISSUE THREAD

**Issue by jmmv** [endbasic/endbasic#144]
If "Caret browsing" (F7) is enabled in Chrome-based web browsers, the behavior of the REPL is erratic: pressing the Arrow Up key to recall a previous command and hitting Enter causes the browser to navigate away from the REPL (because the browser selects the EndBASIC link at the bottom of the page).

I suspect we can work around this issue with better keyboard handling in the web UI. Would be good to know if this is a regression in 0.8 with the replacement of xterm.js with custom code.

**Comment by Protowalker** [comment]
Happens in firefox as well, along with the Vimium extension for both browsers. (Extension might not be fixable -- I've usually had issues on sites with custom text entry)

**Comment by Protowalker** [comment]
Additional issue: in Firefox, pressing `/` puts you into quick find mode. This problem would also be fixed by better keyboard handling, so it might be worth it to make this issue broader.

**Comment by jmmv** [comment]
Interesting. Could easily reproduce what you described in Firefox too. (I had filed this bug report because someone reported problems over email.)

It seems to me that this is just a duplicate of #136? Because the fix you proposed seems to fix both issues. Will update the title of that one and close this as a duplicate.
